import{i as a,S as u}from"./assets/vendor-8c59ed88.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();function f(s){return fetch(`https://pixabay.com/api/?key=43779125-040e3030fad6a4afa34a77542&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`).then(t=>{if(!t.ok)throw new Error("Network response was not ok");return t.json()})}function m(s,t,n){s.innerHTML="";const o=t.hits.map(e=>`<li class="gallery-item">
                    <a class="gallery-link" href="${e.largeImageURL}">
                        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
                    </a>
                    <ul class="info">
                        <li class="info-list">Likes: <span>${e.likes}</span></li>
                        <li class="info-list">Views: <span>${e.views}</span></li>
                        <li class="info-list">Comments: <span>${e.comments}</span></li>
                        <li class="info-list">Downloads: <span>${e.downloads}</span></li>
                    </ul>
                </li>`);s.innerHTML=o.join(""),n.refresh()}const d=document.querySelector('input[name="text"]'),y=document.querySelector("button"),l=document.querySelector(".gallery"),c=document.querySelector(".loader");y.addEventListener("click",()=>{const s=d.value.trim();s!==""?(c.style.display="block",l.innerHTML="",f(s).then(t=>{t.hits.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}):m(l,t,p)}).catch(t=>{console.log(t),a.error({message:"Sorry, there was an error processing your request.",position:"center"})}).finally(()=>{c.style.display="none"})):a.error({message:"Please enter a search term.",position:"center"})});const p=new u(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
